/**
 * scripts/build.ts — build Orkestra menjadi SATU file JS mandiri.
 *
 * Langkah:
 * 1. Baca prompt/*.md → generate src/prompts.gen.ts (prompt ter-embed sebagai string).
 * 2. bun build src/index.ts → dist/orkestra.js (bundle, target bun).
 *
 * Hasil: dist/orkestra.js bisa langsung ditaruh di ~/.config/opencode/plugins/
 * tanpa install apa pun.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// fileURLToPath (bukan new URL(...).pathname): pathname meng-encode spasi jadi
// %20 dan di Windows menghasilkan /C:/... yang lalu ditempeli drive lagi
// oleh resolve() → C:\C:\... (ENOENT deterministik).
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const promptDir = resolve(root, "prompt");
const srcDir = resolve(root, "src");
const distDir = resolve(root, "dist");

function read(name: string): string {
  return readFileSync(resolve(promptDir, name), "utf8").trim() + "\n";
}

const gen = `/**
 * prompts.gen.ts — GENERATED by scripts/build.ts. Jangan edit manual;
 * edit prompt/*.md lalu jalankan \`bun run build\`.
 */
export const PROMPT_MANDOR: string = ${JSON.stringify(read("mandor.md"))};
export const PROMPT_TUKANG: string = ${JSON.stringify(read("tukang.md"))};
export const PERINTAH_ORKESTRA: string = ${JSON.stringify(read("perintah-orkestra.md"))};
`;

mkdirSync(srcDir, { recursive: true });
writeFileSync(resolve(srcDir, "prompts.gen.ts"), gen);
console.log("✓ src/prompts.gen.ts generated");

mkdirSync(distDir, { recursive: true });
const result = await Bun.build({
  entrypoints: [resolve(srcDir, "index.ts")],
  outdir: distDir,
  naming: "orkestra.js",
  target: "bun",
  minify: false,
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}
console.log("✓ dist/orkestra.js built (" + result.outputs.map((o) => o.path).join(", ") + ")");
